Traceback (most recent call last):
  File "experiment_handler_daemon.py", line 305, in <module>
    daemon.start()
  File "/home/nk371/RNASeqPipeline/daemon/daemon.py", line 85, in start
    self.run()
  File "experiment_handler_daemon.py", line 25, in run
    mouse_gtf = config_map['genome_files']
KeyError: 'genome_files'
